# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "221dbd96dfe96ffa7cf563848d762a71"
name = "Visual app"
handle = "visual-app-7"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "checkout-application-development.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
